#!/bin/bash

LOCKFILE=/var/lock/mining

if [ -f $LOCKFILE ]; then
  echo "Mining is currently running."
  echo "Lock is active $LOCKFILE."
  exit 2
fi

touch $LOCKFILE
trap "{ rm -f $LOCKFILE;   }" EXIT

